Group2_Project_All/FA.Project/Fa.Present/Areas/Admin/Controllers/ClassAdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FA.Project.Model;

namespace Fa.Present.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ClassAdminsController : Controller
    {
        private readonly TMSContext _context;

        public ClassAdminsController(TMSContext context)
        {
            _context = context;
        }

        // GET: Admin/ClassAdmins
        public async Task<IActionResult> Index()
        {
            return View(await _context.ClassAdmins.ToListAsync());
        }

        // GET: Admin/ClassAdmins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classAdmin = await _context.ClassAdmins
                .FirstOrDefaultAsync(m => m.ClassAdminId == id);
            if (classAdmin == null)
            {
                return NotFound();
            }

            return View(classAdmin);
        }

        // GET: Admin/ClassAdmins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/ClassAdmins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClassAdminId,FullName,DateOfBirth,Gender,PhoneNumber,Email,Account,Status,AuditTrail,isDelete")] ClassAdmin classAdmin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(classAdmin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(classAdmin);
        }

        // GET: Admin/ClassAdmins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classAdmin = await _context.ClassAdmins.FindAsync(id);
            if (classAdmin == null)
            {
                return NotFound();
            }
            return View(classAdmin);
        }

        // POST: Admin/ClassAdmins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClassAdminId,FullName,DateOfBirth,Gender,PhoneNumber,Email,Account,Status,AuditTrail,isDelete")] ClassAdmin classAdmin)
        {
            if (id != classAdmin.ClassAdminId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(classAdmin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassAdminExists(classAdmin.ClassAdminId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(classAdmin);
        }

        // GET: Admin/ClassAdmins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var classAdmin = await _context.ClassAdmins
                .FirstOrDefaultAsync(m => m.ClassAdminId == id);
            if (classAdmin == null)
            {
                return NotFound();
            }

            return View(classAdmin);
        }

        // POST: Admin/ClassAdmins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var classAdmin = await _context.ClassAdmins.FindAsync(id);
            _context.ClassAdmins.Remove(classAdmin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClassAdminExists(int id)
        {
            return _context.ClassAdmins.Any(e => e.ClassAdminId == id);
        }
    }
}

Group2_Project_All/FA.Project/Fa.Present/Areas/Admin/Controllers/Trainees1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FA.Project.Model;
using FA.Core.Services;
using System.Linq.Expressions;

namespace Fa.Present.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class Trainees1Controller : Controller
    {
        private readonly TMSContext _context;
        private readonly ITraineeServices _traineeServices;
        public Trainees1Controller(TMSContext context, ITraineeServices traineeServices)
        {
            _context = context;
            _traineeServices = traineeServices;
        }
        //// GET: Admin/Trainees
        //public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageIndex = 1, int pageSize = 10)
        //{
        //    ViewData["CurrentPageSize"] = pageSize;
        //    ViewData["CurrentSort"] = sortOrder;
        //    ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        //    if (searchString != null)
        //    {
        //        pageIndex = 1;
        //    }
        //    else
        //    {
        //        searchString = currentFilter;
        //    }

        //    ViewData["CurrentFilter"] = searchString;

        //    Expression<Func<Trainee, bool>> filter = null;

        //    if (!string.IsNullOrEmpty(searchString))
        //    {
        //        filter = c => c.Account.Contains(searchString);
        //    }

        //    Func<IQueryable<Trainee>, IOrderedQueryable<Trainee>> orderBy = null;

        //    switch (sortOrder)
        //    {
        //        case "name_desc":
        //            orderBy = q => q.OrderByDescending(c => c.Account);
        //            break;
        //        default:
        //            orderBy = q => q.OrderBy(c => c.Account);
        //            break;
        //    }

        //    var trainees = await _traineeServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

        //    return View(trainees);


        //    //var tMSContext = _context.Trainees.Include(t => t.ClassBatch);
        //    //return View(await tMSContext.ToListAsync());
        //}


        // GET: Admin/Trainees1
        public async Task<IActionResult> Index()
        {
            var tMSContext = _context.Trainees.Include(t => t.ClassBatch);
            return View(await tMSContext.ToListAsync());
        }

        // GET: Admin/Trainees1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var trainee = await _traineeServices.GetByIdAsync((int)id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }

        // GET: Admin/Trainees1/Create
        public IActionResult Create()
        {
            ViewData["ClassBatchId"] = new SelectList(_context.ClassBatches, "ClassId", "AuditTrail");
            return View();
        }

        // POST: Admin/Trainees1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TraineeId,FullName,DateOfBirth,Gender,PhoneNumber,FamilyPhoneNumber,Email,ExternalEmail,Account,OnboardDate,Status,Remarks,University,Faculty,Skill,ForeignLanguage,Level,CV,AllocationStatus,AuditTrail,isDelete,ClassBatchId")] Trainee trainee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassBatchId"] = new SelectList(_context.ClassBatches, "ClassId", "AuditTrail", trainee.ClassBatchId);
            return View(trainee);
        }

        // GET: Admin/Trainees1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var trainee = await _context.Trainees.FindAsync(id);
            //var trainee = await _context.Trainees.FindAsync(id);
            if (trainee == null)
            {
                return NotFound();
            }
            ViewData["ClassBatchId"] = new SelectList(_context.ClassBatches, "ClassId", "AuditTrail", trainee.ClassBatchId);
            return View(trainee);
        }

        // POST: Admin/Trainees1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TraineeId,FullName,DateOfBirth,Gender,PhoneNumber,FamilyPhoneNumber,Email,ExternalEmail,Account,OnboardDate,Status,Remarks,University,Faculty,Skill,ForeignLanguage,Level,CV,AllocationStatus,AuditTrail,isDelete,ClassBatchId")] Trainee trainee)
        {
            if (id != trainee.TraineeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _traineeServices.UpdateAsync(trainee);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TraineeExists(trainee.TraineeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassBatchId"] = new SelectList(_context.ClassBatches, "ClassId", "AuditTrail", trainee.ClassBatchId);
            return View(trainee);
        }

        // GET: Admin/Trainees1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainee = await _context.Trainees
                .Include(t => t.ClassBatch)
                .FirstOrDefaultAsync(m => m.TraineeId == id);
            if (trainee == null)
            {
                return NotFound();
            }

            return View(trainee);
        }

        // POST: Admin/Trainees1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trainee = await _context.Trainees.FindAsync(id);
            _context.Trainees.Remove(trainee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TraineeExists(int id)
        {
            return _context.Trainees.Any(e => e.TraineeId == id);
        }
    }
}

Group2_Project_All/FA.Project/Fa.Present/Areas/Admin/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FA.Project.Model;

namespace Fa.Present.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TrainersController : Controller
    {
        private readonly TMSContext _context;


        public TrainersController(TMSContext context)
        {
            _context = context;
        }

        // GET: Admin/Trainers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Trainers.ToListAsync());
        }

        // GET: Admin/Trainers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers
                .FirstOrDefaultAsync(m => m.TrainerId == id);
            if (trainer == null)
            {
                return NotFound();
            }

            return View(trainer);
        }

        // GET: Admin/Trainers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Trainers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TrainerId,FullName,DateOfBirth,Gender,PhoneNumber,Email,Account,Status,Type,Unit,Major,Experience,Remarks,AuditTrail,isDelete")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trainer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trainer);
        }

        // GET: Admin/Trainers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers.FindAsync(id);
            if (trainer == null)
            {
                return NotFound();
            }
            return View(trainer);
        }

        // POST: Admin/Trainers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TrainerId,FullName,DateOfBirth,Gender,PhoneNumber,Email,Account,Status,Type,Unit,Major,Experience,Remarks,AuditTrail,isDelete")] Trainer trainer)
        {
            if (id != trainer.TrainerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trainer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainerExists(trainer.TrainerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trainer);
        }

        // GET: Admin/Trainers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainer = await _context.Trainers
                .FirstOrDefaultAsync(m => m.TrainerId == id);
            if (trainer == null)
            {
                return NotFound();
            }

            return View(trainer);
        }

        // POST: Admin/Trainers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var trainer = await _context.Trainers.FindAsync(id);
            _context.Trainers.Remove(trainer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainerExists(int id)
        {
            return _context.Trainers.Any(e => e.TrainerId == id);
        }
    }
}

Group2_Project_All/FA.Project/Fa.Present/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fa.Present</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" >
            <div class="container">
                <div class="imageLogo">
                    <img class="imageLogo" src="~/css/FPTlogo.png" />
                </div>
                 <a class=" navbar-brand" id="BigText" asp-area="" asp-controller="Home" asp-action="Index">
                    Time Manage System</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" id="allColor">
                        <ul class="navbar-nav flex-grow-1" id="linkA">
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Trainee
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Trainees1" asp-action="Create" style="color:black">Create request</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Trainees1" asp-action="Index" style="color:black">All Trainee</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    ClassBatches
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="ClassBatches" asp-action="Create">Create</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="ClassBatches" asp-action="Index">All Class </a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    ClassAdmins
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="ClassAdmins" asp-action="Create">Create</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="ClassAdmins" asp-action="Index">All ClassAdmins</a>
                                </div>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Trainers
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Trainers" asp-action="Create">Create</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Trainers" asp-action="Index">All Trainers</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
        </nav>
    </header>
    <div class="container">

        

        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Fa.Present - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>